# Perception params
perception:
  type: "new" # lab / model

# scanner window params
scanner:
  scanSteps: 5
  scanStartPoint: 0
  scanEndPoint: 512
  scanWindowWidth: 64

# tracker params
tracker:
  trackingBoxWidth: 200
  topOffset: 0
  bottomOffset: 0
  sacleRatio: 0.4

# contour params
contour:
  minArea: 100
  split: False

roi:
  enable_roi: True
  p1: 
  - 0
  - 0
  p2:
  - 350
  - 0
  p3:
  - 10
  - 720
  p4:
  - 0
  - 720
  p5: 
  - 830
  - 0
  p6:
  - 1280
  - 0
  p7:
  - 1280
  - 720
  p8: 
  - 1270
  - 720